### ISSUE TITLE
Possible to improve the output reporting?

### ISSUE THREAD

**Issue by flowt-au** [amiceli/vitest-cucumber#101]
Hi. I am not sure if this is a question for you or for Vitest in general.

A major reason for wanting to use Gherkin is so non-programmers can read the tests and make meaningful comments on whether it meets their expectations. And in some situations for them to actually write the tests as a way for them to specify the requirements using examples.

So, I am wondering if it would be difficult to make the tests reports more detailed. So, given this feature:
```gherkin
Feature: I have an awesome calculator

  Background:
    Given I have a calculator instance

  Scenario Outline: Multiply two numbers
    When I multiply <num1> by <num2> for "<id>"
    Then the result of test "<id>" should be <result>

    Examples:
        | num1 | num2 | result | id    |
        | 1    | 5    | 5      | one   |
        | 2    | 3    | 6      | two   |
        | 7    | 5    | 35     | three |
```

I get the following in the console and the same in the Vitest report:
![Greenshot 2024-07-15 13 44 10](https://github.com/user-attachments/assets/ade10275-314d-4a11-bb78-6c1536eef3e0)

I am wondering whether instead of eg `When I multiply <num1> by <num2> for "<id>"` the report line could read 
```
When I multiply 1 by 5 for "one"
Then the result of test "one" should be 5
``` 
and 
```
When I multiply 2 by 3 for "two"
Then the result of test "two" should be 6
```
etc. 

That way, the client can read the test reports and make sense of which tests worked and whether or not that is what they intended.

Merci beaucoup encore, Murray

**Comment by amiceli** [comment]
It's good idea ;) I will check how to improve report.
I will update this issue when you can test it ;).

**Comment by amiceli** [comment]
I added it, you'll see update with `3.4.3` version ;).

**Comment by flowt-au** [comment]
Wow, thanks so much! I will use it today. :-)

**Comment by flowt-au** [comment]
Works well. Thanks again for the quick turnaround. :-)
