### ISSUE TITLE
Suggestion for the future: pending, skip, todo, etc

### ISSUE THREAD

**Issue by flowt-au** [amiceli/vitest-cucumber#105]
Possibly for your future list...

It would be great to be able to mark tests as pending, skip and todo. I know vitest supports these ([https://vitest.dev/api/#test-todo](https://vitest.dev/api/#test-todo)) but not in a very useful way from a documentation perspective, and vitest-cucumber doesn't seem to support the vitest approach anyway. 

The `todo` is especially important for me because I like to write the complete feature file then start coding incrementally. It is great to be able to mark a step with `todo` so the test output can print something like `ToDo: When the user clicks the button` and have an appropriate icon (ie not the green tick, or perhaps an orange tick or empty square, or whatever). This way as I develop using the feature-first approach I (and other team members) can see in the report what still needs to be worked on.

This is better than "pending" in my view, and is of course different to "skip" which implies the test and code has been written but you do not want to test it for some reason.

(As an aside I previously used Cypress and Cypress Cucumber Preprocessor and had to hack it to get this functionality)

I tried importing `test` from Vitest and calling it in the step but Vitest didn't like that!
```js
import { expect, test } from 'vitest';

    When(`I multiply <num1> by <num2> for "<id>"`, () => {
      test.skip(); // Nope!
      product = calculator.multiply(num1, num2);
    })
```
it throws: `Error: Calling the test function inside another test function is not allowed. Please put it inside "describe" or "suite" so it can be properly collected.`

So, I am imagining something like:
```js
ScenarioOutline(`Multiply two numbers`, ({ Given, When, Then, skip, pending, todo }, variables) => {

    When(`I multiply <num1> by <num2> for "<id>"`, () => {
      todo();
    })
})
```
which would "skip" the test but output something like:
```
? ToDo: When I multiply 1 by 5 for "one"
```
Where `?` is an appropriate icon and colour.

What do you think?

Cheers,
Murray
```

**Comment by amiceli** [comment]
Currently `Scenario` uses `test.every` to run steps, so it's normal if vitest throw an error if you use `test` in a step.

I know vitest pass current test as params and we can call `skip`, for example : 

~~~js
describe(`example`, () => {
    test(`I want skip it`, (args)  =>{
        args.skip()
        expect(true).toBeFalsy()
    })
})
~~~

I'm checking how to implement this in vitest-cucumber like : 

~~~js
s.Then(`I can't use Vue {number}`, (version, ctx) => {
    ctx.skip()
    expect(version).toEqual(2)
})
~~~

`ctx` will be last params of steps.

I will also implement a warning like message if steps are pending/skipped.
It's opinionated for me, it's a goal of vitest-cucumber to prevent missing, skipped steps etc.

I will update this issue when something can be test ;).

**Comment by flowt-au** [comment]
Thanks. That was my first thought about a way to implement a solution too. But then I discovered that while `ctx.skip()` works, there is no `ctx.todo()`, both of which are important, in my view. And, having a more meaningful report message is desirable too. Hence my suggestion to provide custom `skip()` and `todo()` functions. Just a thought.
Cheers,
Murray

**Comment by amiceli** [comment]
I understand `todo` and `skip` are both important but in report (in console) both are tagged skipped : 

![image](https://github.com/user-attachments/assets/86d250fc-e87a-44a7-b0bf-fa9bed0443f7)

To start I will pass `ctx` in steps params to allow `skip`.
For `todo` I will check if it's possible without break `test.every` used in `Scenario`.

**Comment by flowt-au** [comment]
> report (in console) both are tagged skipped

Yes, indeed they are. And that is what I was hoping could be overcome by using a custom function (instead of the Vitest functions) so the report is more useful.

>   To start I will pass ctx in steps params to allow skip.
Great, that will be a big help.

Anyway, I will let you get on with your work. Thanks again. :-)

**Comment by amiceli** [comment]
HI @flowt-au ,

I've published a beta version `3.5.0-beta.10` who pass `TaskContext` in each step.
So you can call `skip`, for example : 

~~~javascript
f.Background((b) => { // same for Scenario and ScnearioOutline
    b.Given(`I use vitest-cucumber`, (ctx) => {
        ctx.skip()
    })
})
~~~

In console you'll see `Given` step as skipped.
You can test it, before publish a stable I want to log a warning message if a step is skipped ;).

And for information I has to update deps to Vitest 2.

**Comment by flowt-au** [comment]
That's great! Thank you. I will test it today. :-)

**Comment by flowt-au** [comment]
Thanks, works well. 

FYI: [Support for ctx.todo()](https://github.com/vitest-dev/vitest/issues/6212)
;-)

**Comment by amiceli** [comment]
I will publish a stable version.
I'm following your issue on vitest, depending on what happens I will re-open this issue and maybe include `todo` etc.

**Comment by amiceli** [comment]
I've publish new stable version `3.4.4`.
