### ISSUE TITLE
Testing your test framework

### ISSUE THREAD

**Issue by jclaveau** [amiceli/vitest-cucumber#16]
You're work seems very interesting but I can't integrate such an important piece of a stack without it to be tested and having enough coverage. Do you plan to do it?

Simply using the tests cases of jest-cucumber may save a lot of time to achieve this: https://github.com/bencompton/jest-cucumber/tree/master/specs

Thanks for your work!

**Comment by amiceli** [comment]
Hi @jclaveau ,

Thank you for your message, It is a pleasure.
Tests and coverage are important for me, so yes I work on it.

If you want to take a look, I update unit tests in [describe-feature.spec.ts](https://github.com/amiceli/vitest-cucumber/blob/main/src/vitest/__tests__/describe-feature.spec.ts) for new version 2.0.0.
And I will check a way to show coverage results.

I will never stop to work on it ^^. It's a project I use in many side projects and we use it where I work.

Currently I'm working to add `Background` and `Rules` to vitest-cucumber.

Thanks for your link to `jest-cucumber`, I'm reading that.

**Comment by jclaveau** [comment]
Nice, I will keep an eye on your progress (Background is also required for me to switch).

Bonne continuation!

**Comment by amiceli** [comment]
Merci @jclaveau  ;)

**Comment by amiceli** [comment]
@jclaveau Rule is done, I start on `Background` ;).

**Comment by amiceli** [comment]
@jclaveau `Background` is now available with version `3.3.0` ;).

**Comment by jclaveau** [comment]
> @jclaveau `Background` is now available with version `3.3.0` ;).

I have too much work to move to your framework for now but I keep an eye on it. Thank you!
