### ISSUE TITLE
Incompatibility with browser mode?

### ISSUE THREAD

**Issue by charlieforward9** [amiceli/vitest-cucumber#176]
When I try migrating my jsdom-based testing into browser mode, all of my vitest-cucumber tests fail in the browser with the following error message:
```
TypeError: (0 , import_node_path.dirname) is not a function
 - /node_modules/.vite/deps/@amiceli_vitest-cucumber.js:5277:54
 - /node_modules/.vite/deps/@amiceli_vitest-cucumber.js:5281:25
```

Throwing from the line in my file that calls `loadFeature`, from this library. Is there any plan to get this plugin to work with browser mode? 

I specifically use vitest-cucumber for my component/e2e testing, which is the most relevant tests to be runniing in the browser, so it makes sense to see this included. 

I tried this on my original version of 3.9.0, bumped to 4.2.0, same issue

Maybe i am just making a simple mistake?  Thanks

**Comment by amiceli** [comment]
I make a test on [vitest-browser-vue](https://github.com/vitest-dev/vitest-browser-vue) project.
I've same error, I'm working on a fix ;).

**Comment by charlieforward9** [comment]
Now I am seeing `TypeError: Failed to fetch dynamically imported module`

**Comment by amiceli** [comment]
I'm still working on it, I didn't publish a beta version with fix.
