### ISSUE TITLE
Examples of how to use the package

### ISSUE THREAD

**Issue by ReevMich** [amiceli/vitest-cucumber#20]
Is this a plugin or is it standalone? How does a vite project look with this package in use?
Also can this be used with e2e tests?

**Comment by amiceli** [comment]
About`vitest`, vitest can be used [without vite](https://github.com/vitest-dev/vitest/discussions/3362).
So you can use `vitest-cucumber` in any project using `vitest`.

`vitest-cucumber` is just a tool, not a plugin.
When you run unit tests with that, it uses vitest : 
- `Feature`, `Scenario` for example, they call `describe`
- steps like `Given`, `Then` use `test` / `test.each`
- hooks like `BeforeAllScenarios` use `beforeAll`, `afterAll` etc

Main goal is to follow Gherkin rules in unit tests : don't forget a Scenario or Examples for a Scenario Outline etc.

For tests e2e I will commit an example, I will post a message in this issue when it's done.

**Comment by amiceli** [comment]
@ReevMich I did some research for e2e tests.
Like I read, vitest isn't used for e2e tests rather than Cypress for example.

But searching in vitest doc I found a page for [browser mode](https://vitest.dev/guide/browser#:~:text=Drawbacks%20%E2%80%8B&text=The%20browser%20mode%20feature%20of,not%20yet%20been%20ironed%20out.).
I never used it maybe it can be useful 😉 

Maybe a day I will make a `cypress-cucumber` 😄

**Comment by reinerBa** [comment]
Would you please add an example folder in this repository or create an example-repository?
I would like to see how it all likes to be ready.

**Comment by amiceli** [comment]
Yes I can make an examples folder, I will do it.
Before start which informations are missing in README ? It's useful for me to know it ;).

**Comment by reinerBa** [comment]
An information how the test can be started would be usefull. Like the additional lines in the scripts section in package.json.
Are any additional config files necessary?
Are there any naming conventions for the unit-test-files?
Which additional files are necessary for your plugin, feature files, test files, run files?

**Comment by amiceli** [comment]
`vitest-cucumber` is a tool not a plugin, so you don't need to add or update a config file.
You just have to run your tests with vitest, in `package.json` a script like `"test:unit": "vitest"` is enough ;).
I will update README for that ;)

To run test you need  a `.feature file`, I will show it in `examples` folder. I'm working on it ;).
I'm working on a side project using `vitest-cucumber`, I will make public asap. It will be a good example ;).

**Comment by amiceli** [comment]
@reinerBa I added an example folder : https://github.com/amiceli/vitest-cucumber/tree/main/examples.
I hope you like it ;).

I've updated README following your messages, thank you ;)
