### ISSUE TITLE
Feature Request: Codegen / Snippet Tool

### ISSUE THREAD

**Issue by charlieforward9** [amiceli/vitest-cucumber#81]
It would be incredible to have a tool that takes the `.feature` file that is written manually, and automatically generate the `describeFeature` test. 

Maybe this would simply be a CLI script?

**Comment by amiceli** [comment]
You can check on README.
I created a CLI to generate `spec.ts` file from `feature` file.

Example : `node node_modules/@amiceli/vitest-cucumber/dist/cli-generate.js  features/example.feature src/__tests__/example.spec.ts`

**Comment by charlieforward9** [comment]
Small tweak on the path: it's actually in the `scripts` folder, not `dist`.

This is exactly what I am looking for though, thank you for building this! Very awesome.

👏🏼

**Comment by amiceli** [comment]
I'll update README to fix script example.

**Comment by amiceli** [comment]
`script` is for version before `3.3.0` ;) 
Now it's `dist` and cli-generate` supports `Background`.

**Comment by charlieforward9** [comment]
On [3.3.1-beta.1](https://www.npmjs.com/package/@amiceli/vitest-cucumber/v/3.3.1-beta.1) I cannot find the `cli-generate.js` folder in `node_modules`.

**Comment by amiceli** [comment]
I fixed it in new beta version `3.3.1-beta.2`.

**Comment by charlieforward9** [comment]
Working, thank you.
