### ISSUE TITLE
Question re variables

### ISSUE THREAD

**Issue by flowt-au** [amiceli/vitest-cucumber#97]
Hi. Thanks for your work!
Am I right that unlike regular Cucumber, a Gherkin clause like:
```gherkin
When I click on "official docs" link
```

must be matched with a step like:
```js
When(`I click on "official docs" link`, () => {
```

rather than
```js
When(`I click on {string} link`, (linkText) => {
```

unless I use Scenario Outline / Example table?

Or have I missed something?
Cheers,
Murray

**Comment by amiceli** [comment]
If you have a step like 
~~~gherkin
When I click on "official docs" link
~~~

Yes in your tests you should use : 

~~~javascript
When(`I click on "official docs" link`, () => {
~~~

But if you want a `Scenario` with many links, you should use `Scenario Outline`.
In `Scenario Outline` variables use `<`, `>` symbols instead of `{`, `}`. 
You can check [Scenario Outline Gherkin docs](https://cucumber.io/docs/gherkin/reference/#scenario-outline).

In **vitests-cucumber** I pass `Scenario Outline` variables in parent callback instead of step : [example in README](https://github.com/amiceli/vitest-cucumber?tab=readme-ov-file#scenario-outline-and-examples).

A simple example with `<link>` variable : 

~~~gherkin
Scenario Outline: I click
    Given User on cool website
    When  I click on <link> link
    Then  I see "Cool website" in tab title

    Examples:
        | link          |
        | official docs |
        | FAQ           |
        | Homepage      |
~~~

In unit tests : 

~~~javascript
ScenarioOutline(`I click`, ({Given, When, Then}, variables) => {
    // variables.link can be used in any step
    Given(`User on cool website`, () => {})
    When(`I click on <link> link`, () => {})
    Then(`I see "Cool website" in tab titile`, () => {})
})
~~~

**Comment by flowt-au** [comment]
Thanks yes, that is how I understood it. 

Do you have any plans to handle variables without Scenario Outlines, like Cucumber does? eg
```gherkin
When the user enters "Milk" and $2.50 into the form 
```
has a matching step like:
```js
When(`the user enters {string} and ${number} into the form `, (string1, number1) => {})
```

Thanks again for what you have done.
Murray

**Comment by amiceli** [comment]
I never used variable without `Scenario Outline` but I will take a look.
I'm reading [parameters type doc](https://github.com/cucumber/cucumber-expressions#readme) ;).

I will update this issue if I plan/start this feature.

**Comment by flowt-au** [comment]
Thanks. It is a useful pattern, especially where there are only a couple of variables. eg username and password. Then you don't need a Scenario Outline and a table with just one row. I have often also coded tests with just one number and it reads better to have it "inline" rather than in the Example table. :-)

**Comment by robmoffat** [comment]
Hi, 

Just came across this project today and I think it looks like a really great idea.   I want to run cucumber in the browser and I think using this with vitest is probably the best way I've found to do it.  

WRT to the above, the syntax of cucumber is called 'Gherkin'  and you can use the parser here rather than write your own one:   https://github.com/cucumber/gherkin?tab=readme-ov-file#javascript

FWIW I have the same issue as @flowt-au 

I might be able to help with this generally

**Comment by amiceli** [comment]
Yes when I started project I tried `cucumber/gherkin` but I prefered create my own parser.
For step with expression I started to work on it, I will publish my branch when the code will be 'readable'.

And I will publish a beta version when I have made something "usable" :).

**Comment by flowt-au** [comment]
> but I prefered create my own parser.

I was thinking about this and given how useful this project is I was wondering whether using the "official" gherkin parser as suggested by @robmoffat would ultimately enable users to have access to the full range of the Gherkin syntax like `tags` etc. I can imagine that in the future there will be requests for a fuller implementation of Gherkin and leveraging the existing parser seems attractive. Just a thought. And my level of expertise and available time means I cannot help, sorry to say. 
Anyway, just musing. I am grateful for what you have done so far. Merci.
Murray

**Comment by amiceli** [comment]
@flowt-au  De rien, ça fait plaisir 😊.

For Gherkin parser, I know it can be surprising, but I won't use `@cucumber/gherkin`.
I prefer use custom parser and convert Gherkin into domain classes like `Step`, `StepAble`, `Scenario` etc.
I've implemented `Scenario`, `Rule`, `tags` etc and I will include also DocStrings, data table, expression step (of course ;)) etc
I know it's opiniated but vitest-cucumber is a side / fun / challenge project for me.
Maybe it's a mistake, we'll see ;).

For expression steps I start to work with regex, I will push my branch when code will be "readable".

**Comment by flowt-au** [comment]
@amiceli Sounds great! Thanks again and I hope the project remains fun! ;-)

**Comment by flowt-au** [comment]
Hi. Further to this. I notice that if I use double quotes in a Given with a Scenario Outline it throws an error.

So, this pair works:
```gherkin
Given a person in organisation=<organisation> with firstname=<firstname>, lastname=<lastname>, email=<email> and mkey=<mkey>
```
```js
Given(`a person in organisation=<organisation> with firstname=<firstname>, lastname=<lastname>, email=<email> and mkey=<mkey>`, () => {})
```
But this (normal Gherkin syntax for strings) throws the error: `StepAbleUnknowStepError: 
 Given a person in organisation="<organisation>" with firstname="<firstname>", lastname="<lastname>", email="<email>" and mkey="<mkey>" doesn't exist`
```gherkin
Given a person in organisation="<organisation>" with firstname="<firstname>", lastname="<lastname>", email="<email>" and mkey="<mkey>"
```
```js
Given(`a person in organisation="<organisation>" with firstname="<firstname>", lastname="<lastname>", email="<email>" and mkey="<mkey>"`, () => {})
```
Given you are working on the Gherkin parameters, I wanted to mention that the Scenario Outline parsing will probably need updating too? Or maybe I am doing it incorrectly?

Thanks again,
Murray

**Comment by amiceli** [comment]
I don't reproduce this bug.
I create a feature with your example like : 

~~~gherkin
Feature: Background run before scenario tests
    Scenario Outline: Simple scenario
        Given a person in organisation="<organisation>" with firstname="<firstname>", lastname="<lastname>", email="<email>" and mkey="<mkey>"
        Then  it is ok

        Examples:
            | organisation | firstname | lastname | email        | mkey  |
            | awesome      | test      | test     | test@test.fr | again |

~~~~

And I did a unit tests like this : 

~~~js
const feature = await loadFeature(`ex.feature`)

describeFeature(feature, (f) => {
    f.ScenarioOutline(`Simple scenario`, (s, variables) => {
        s.Given(`a person in organisation="<organisation>" with firstname="<firstname>", lastname="<lastname>", email="<email>" and mkey="<mkey>"`, () => {
            expect(variables.organisation.includes(`a`)).toBeTruthy()
        })
        s.Then(`it is ok`, () => {
            expect(variables.firstname.includes(`e`)).toBeTruthy()
        })
    })
})
~~~

Do you have difference in your code ?

**Comment by flowt-au** [comment]
My sincere apologies. Yes, it does work. I cleared everything and retested my code and it just started working! Sorry for the time-waste. 
Regards,
Murray

**Comment by flowt-au** [comment]
My sincere apologies. Yes, it does work. I cleared everything and retested my code and it just started working! Sorry for the time-waste. 
Regards,
Murray

**Comment by amiceli** [comment]
No problems ;).
Just a thing, to make it more readable (Gherkin practice) you can split your `Given` ;).
Like : 
~~~gherkin
Given a person in organisation=<organisation>
And the person has firstname=<firstname> # or And  it's firstname is <firstname>
And the person has lastname=<lastname>
And the person has email=<email>
And the person has mkey=<mkey>
~~~~

**Comment by flowt-au** [comment]
Yes, thanks!

**Comment by amiceli** [comment]
@flowt-au It isn't a stable version but you can test it with `3.5.0-beta.1` version.
Currently I added : 
- `{string}` with simple or double quotes
- `{number}` with number but `$` not yet
- `{float}` detect number with dot but `$` not yet

Expression works with `Scenario` and `Background` in `Feature` and/or `Rule`.
I'm searching if expression works/is useful with `Scenario Outline` before add it ;).

**Comment by amiceli** [comment]
An example

~~~gherkin
Feature: Example
    Scenario: scenario with expression
        Given I use "Vue" 3.2
        Then  I can't use Vue 2
        And   I use typescript
~~~

~~~javascript
describeFeature(feature, (f) => {
    f.Scenario(`scenario with expression`, (s) => {
        s.Given(`I use {string} {float}`, (framework: string, version: number) => {
            expect(framework).toEqual(`Vue`)
            expect(version).toEqual(3.2)
        })
        s.Then(`I can't use Vue {number}`, (version) => {
            expect(version).toEqual(2)
        })
        s.And(`I use typescript`, (...params) => {
            expect(params.length).toBe(0)
        })
    })
})
~~~

**Comment by flowt-au** [comment]
Great! This works. :-)

**Comment by amiceli** [comment]
Nice, I'm still working it before merge and publish a stable version.
I will update this issue when a stable version is published ;).

**Comment by amiceli** [comment]
To debrief, I'm working on it to rebase with step expressions like `{string}` ;).

**Comment by amiceli** [comment]
I've published a beta version `3.5.0-beta.2` with `{string}`, `{number}` and `{float}` for step expressions.

I'm testing this version in my projects and coding to provide a config to add custom expressions like `{list}` who matches something like "one, two, three".

**Comment by amiceli** [comment]
My tests are OK.
I'm going to publish a stable version who provides `{string}`, `{number}`, `{float}` and `{list}` to starts with step expressions.
Version will be `3.5.0` and I will update docs.

A Gherkin example : 

~~~gherkin
Given  I use "Vue" 3.2
~~~

Expressions value are passed after step context : 

~~~typescript
s.Given(`I use {string} {float}`, (ctx : TaskContext, framework : string, version : number) => {
    expect(framework).toEqual(`Vue`)
    expect(version).toEqual(3.2)
    expect(
        ctx.task.name,
    ).toEqual(`Given I use "Vue" 3.2`)
})
~~~

**Comment by amiceli** [comment]
`3.5.0` is published ;).

**Comment by flowt-au** [comment]
Fantastic news! Thanks again. I will implement today. :-)

PS: Unrelated: your Olympic Opening Ceremony - c'est manifique! Bravo! :-)
