### ISSUE TITLE
load and describe feature mismatch

### ISSUE THREAD

**Issue by charlieforward9** [amiceli/vitest-cucumber#98]
This error is throwing: `Argument of type 'Readonly<Feature>' is not assignable to parameter of type 'Feature'.
  Type 'Readonly<Feature>' is missing the following properties from type 'Feature': checkIfScenarioExists, scenarioShouldNotBeOutline, scenarioShouldBeOutline`

When I try to pass the `loadFeature` return value into `describeFeature`.

**Comment by amiceli** [comment]
I don't why my projects don't throw this error ^^.
I'm fixing it.

**Comment by amiceli** [comment]
I've published a new version with this fix `3.4.2`.

**Comment by charlieforward9** [comment]
Thank you for the incredibly fast turnover. We are completing all of our testing now after a long period of wait, and we should have #79 docs coming out soon!
